<?php

namespace App\Models;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Tymon\JWTAuth\Contracts\JWTSubject;//Needed : for the JWT

class Admin extends Authenticatable
{

    public $timestamps = true ;
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */


     // #accepts ALL records/rows  ##Wrong security implement !!
     protected $guarded =[
         //null

     ];


      protected $fillable =[
        'name', 'email' , 'password','mobile'

     ];


        // get admin.name insted of admin.id in the URL : more fine !
//    public function getRouteKeyName()
//    {
//        //to be retrived insted of its id
//        return 'name';
//        //return parent::getRouteKeyName(); // TODO: Change the autogenerated stub
//    }

    public function roles() {
        return $this->belongsToMany(Role::class, 'user_roles');
    }
    public function isAdministrator() {
        return $this->roles()->where('name', 'admin')->exists();
    }


    public function getJWTIdentifier()
    {
        // TODO: Implement getJWTIdentifier() method.
        return $this->getKey();
    }

    public function getJWTCustomClaims()
    {
        // TODO: Implement getJWTCustomClaims() method.
        return [];
    }

}
